language: go
sudo: required
services:
- docker
go:
- 1.9
jobs:
  include:
  - stage: test
    script:
    - go test -v ./...
  - stage: build docker image
    script:
    - export VERSION_NUMBER=$(git describe --tags --always)
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t aoepeople/gitlab-crucible-bridge:$VERSION_NUMBER .
    - docker push aoepeople/gitlab-crucible-bridge:$VERSION_NUMBER
  - stage: release on github
    script:
    - ./build.sh
    deploy: 
      provider: releases
      api_key:
        secure: $GITHUB_TOKEN
      file_glob: true
      file: gitlab-crucible-bridge-*  
      skip_cleanup: true
      on:
        tags: true