language: go
sudo: required
services:
- docker
go:
- 1.9
env:
- DEP_VERSION="0.4.1"
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
jobs:
  include:
  - stage: test
    script:
    - dep ensure
    - go test -v ./...
  - stage: build docker image
    script:
    - export VERSION_NUMBER=$(git describe --tags --always)
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t aoepeople/gitlab-crucible-bridge:$VERSION_NUMBER .
    - docker push aoepeople/gitlab-crucible-bridge:$VERSION_NUMBER
  - stage: release on github
    script:
    - "./build.sh"
    deploy:
      provider: releases
      api_key:
        secure: rLkOK/0ODiarsv69Vd65sF2pAVevMTxZtuUFauXG7tdEjVgqfa8C6SZcR2IrBHXrwv7dyReMROYDd0iHlAPjgb0y2U6d8kLSR2RB1q83FKo5qBPti4PogA2jqEb0MT/bueADfxMOYQj6AvDU/RTxtUKA5nbl7kJREGf3JmHFr8LIPO9G/6uYAeGVSf/80QaWCrtmN/310Bv6PFcCkocN7Hp5LXYYDM5BTw/mBET56YRZQXzLkDcqY96MzAkBju0iMUbe7W+YJxCrysr5kUggI0oRnpy3Nt5hWJVo3y89RFCLAOjR4iqmmnAqS/xSui9r0pg5UXgRku/cM6KbSY+UT+X7o8Vcpc/l34xbcMn6b33cmw8eoqHEIQL1dEOmTWspaKiTg0M6nvxJXV0vbMbZngR8Vx8TDpz2+WsCsSiAdGoR6jSZIVl5a9z2J83lQCFjIC/+udxfxn+w5xApwawrRWm2VRtG6t73nnejFoc5EGPcM90qvCFCHAXeDWBC8BABTs5sByPMGgmQbJBxdOocFAKBpXR1ISlASv1QZkfAgYzL27WSms75jhIRd4OgZCkHyCTVZ/o08PqUXQWmhfkymylkGgSZy2+XmzOA5VPTD5irelsB12Fa0UKy5TcGnDpdu1W3rnrtep2C9BssKwoDMEDWY2YRHkE6YChj/+orSeo=
      file_glob: true
      file: gitlab-crucible-bridge-*
      skip_cleanup: true
      on:
        tags: true