language: go
sudo: required
services:
- docker
go:
- 1.9
jobs:
  include:
  - stage: test
    script:
    - go test -v ./...
  - stage: build docker image
    script:
    - export VERSION_NUMBER=$(git describe --tags --always)
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t aoepeople/gitlab-crucible-bridge:$VERSION_NUMBER .
    - docker push aoepeople/gitlab-crucible-bridge:$VERSION_NUMBER
  - stage: release on github
    script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o gitlab-crucible-bridge-linux-amd64 .
    deploy: 
    provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: gitlab-crucible-bridge-linux-amd64
    skip_cleanup: true
    on:
      tags: true